### ISSUE TITLE
 __hash__ method should return an integer

### ISSUE THREAD

**Issue by fm-chen** [fair-search/fairsearchcore-python#3]
Hi there, I was trying to test the code provided on the project page, but I cannot run `fair.compute_fail_probability(mtable)` because it gives me a type error as follow:

---------------------------------------------------------------------------

TypeError: __hash__ method should return an integer

---------------------------------------------------------------------------

Any idea?

Many thanks!!!

**Comment by ivankitanovski** [comment]
Could you provide the exact steps of what you are doing? 

Following the example in the README should work great
```
k = 20 # number of topK elements returned (value should be between 10 and 400)
p = 0.25 # proportion of protected candidates in the topK elements (value should be between 0.02 and 0.98) 
alpha = 0.1 # significance level (value should be between 0.01 and 0.15)

# create the Fair object 
fair = fsc.Fair(k, p, alpha)

# create an mtable using alpha unadjusted
mtable = fair.create_unadjusted_mtable()
>> [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3]

# analytically calculate the fail probability
analytical = fair.compute_fail_probability(mtable)
>> 0.11517506930977106 

# create an mtable using alpha adjusted
mtable = fair.create_adjusted_mtable()
>> [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]

# again, analytically calculate the fail probability
analytical = fair.compute_fail_probability(mtable)
>> 0.10515247355215251

```

**Comment by fm-chen** [comment]
> Could you provide the exact steps of what you are doing?
> 
> Following the example in the README should work great
> 
> ```
> k = 20 # number of topK elements returned (value should be between 10 and 400)
> p = 0.25 # proportion of protected candidates in the topK elements (value should be between 0.02 and 0.98) 
> alpha = 0.1 # significance level (value should be between 0.01 and 0.15)
> 
> # create the Fair object 
> fair = fsc.Fair(k, p, alpha)
> 
> # create an mtable using alpha unadjusted
> mtable = fair.create_unadjusted_mtable()
> >> [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3]
> 
> # analytically calculate the fail probability
> analytical = fair.compute_fail_probability(mtable)
> >> 0.11517506930977106 
> 
> # create an mtable using alpha adjusted
> mtable = fair.create_adjusted_mtable()
> >> [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]
> 
> # again, analytically calculate the fail probability
> analytical = fair.compute_fail_probability(mtable)
> >> 0.10515247355215251
> ```

Hi Ivan, thank you so much for the reply. I figured it out now.
I think there should be some dependency issues with my virtual environment because the code works fine on Colab.

**Comment by hosseinfani** [comment]
#4
